-- [Basic SELECT]
-- 1. 춘 기술대학교의 학과 이름, 계열 표시.(단, 출력 헤더는 "학과 명", "계열"로 표시)
SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2. 학과의 학과 정원 
SELECT DEPARTMENT_NAME||'의 정원은'|| CAPACITY||'명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 국문학과 여학생 중 휴학중인 여학생 출력 (TB_DEPARTMENT통해 조회)
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN, 8,1) = 2 AND ABSENCE_YN = 'Y' 
        AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                               FROM TB_DEPARTMENT                
                               WHERE DEPARTMENT_NAME = '국어국문학과');

-- 4. 도서관 대출 도서 장기 연체자
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5. 입학정원 20명 이상 30명 이하인 학과 이름, 계열
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 

-- 6. 총장 이름
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7. 학과 지정안된 학생 
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. 선수과목 여부 확인, 선수과목 존재하는 과목번호 조회
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 계열 조회
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10. 02학번 전주 거주자 모임. 휴학한 사람 제외, 재학중인 학생 학번, 이름, 주민번호 조회
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '%전주%' AND SUBSTR(ENTRANCE_DATE, 1,2) = '02' AND ABSENCE_YN = 'N';

--[Additional SELECT - 함수]
-- 1. 영문과(학과코드002) 학생들 학번, 이름, 입학년도를 입학년가 빠른 순으로 조회
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2. 이름이 세글자가 아닌 교수의 이름, 주민번호 조회
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3. 남교수 이름, 나이 조회(나이 적은 사람->많은 사람)
SELECT PROFESSOR_NAME 교수이름, EXTRACT(YEAR FROM SYSDATE)-((SUBSTR(PROFESSOR_SSN, 1, 2))+1900) 나이
FROM TB_PROFESSOR
WHERE (SUBSTR(PROFESSOR_SSN, 8,1) = 1)
ORDER BY 나이 DESC;

-- 4. 성 제외한 교수 이름 
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

-- 5. 재수생 입학자 조회 (19살에 입학하면 재수X)
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6))) > 19; 

-- 6. 2020년 크리스마스 요일
SELECT TO_CHAR(TO_DATE('20201225'), 'DAY') 요일
FROM DUAL;

-- 7. 
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'),'YYYY'),
       TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY'), TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY')
FROM DUAL;

-- 8. 2000년도 이전 학생들 학번, 이름
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE ENTRANCE_DATE < '00/01/01';

-- 9. 학번 A517178인 한아름 학생 학점 총 평점 (반올림하여 소수점 이하 한자리까지 표시)
SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10. 학과별 학생 수 구하기
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11. 지도교수 X 학생 수
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12. 학번 A112113인 김고운 학생 년도 별 평점(점수는 반올림하여 소수점 이하 한 자리까지 표시)
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

-- 13. 학과 별 휴학생 조회 (학과번호, 휴학생 수 표시)
SELECT DEPARTMENT_NO 학과번호, COUNT(DECODE(ABSENCE_YN, 'Y', 1)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

-- 14. 동명이인 학생 이름 (이름, 학생 수 표시)
SELECT STUDENT_NAME, COUNT(*)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY STUDENT_NAME;

-- 15. 학번 A112113인 김고운 학생 년도, 학기 별 평점, 년도 별 누적 평점, 총 평점
SELECT SUBSTR(TERM_NO, 1, 4) 년도, SUBSTR(TERM_NO, 5, 2) 학기, ROUND(AVG(POINT), 1) 평균
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2))
ORDER BY SUBSTR(TERM_NO, 1, 4); 