-- 1. 70년대 생(1970 ~ 1979)중 여자이면서 전씨인 사원의 이름과 주민번호, 부서 명, 직급 조회
-- [ORACLE 구문]

-- [ANSI 표준 구문]
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
    JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
    JOIN JOB USING (JOB_CODE)
WHERE (SUBSTR(EMP_NO, 1, 2) BETWEEN '70' AND '79')
      AND SUBSTR(EMP_NO, 8, 1) = 2
      AND EMP_NAME LIKE '전%';