-- 1. 과목유형 테이블(TB_CLASS_TYPE) 입력
INSERT INTO TB_CLASS_TYPE VALUES('01', '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES('02', '전공선택'); 
INSERT INTO TB_CLASS_TYPE VALUES('03', '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES('04', '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES('05', '논문지도');

-- 2. 학생들 정보가 포함되어 있는 학생일반정보 테이블 만들기
CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, STUDENT_ADDRESS 주소
    FROM TB_STUDENT;

SELECT * FROM TB_학생일반정보;

-- 3. 국문학과 학생 정보만 포함된 학과정보 테이블 생성
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO 학번, STUDENT_NAME 학생이름, TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1, 6)), 'YYYY/DD/MM') 출생년도, PROFESSOR_NAME 교수이름
FROM TB_STUDENT S
     JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
     JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT * FROM TB_국어국문학과;

-- 4. 현 학과들 정원 10%증가 (반올림 사용해 소수점 자릿수 생기지 않도록)
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY*1.1);

SELECT * FROM TB_DEPARTMENT;
-- 5. 학번 A413041인 박건우 학생의 주소가 "서울시 종로구 숭인동 181-21"로 변경
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO = 'A413042';

-- 6. 학생정보 테이블에서 주민번호 뒷자리 저장 X (EX. 830530-2124663 -> 830530)
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

SELECT STUDENT_SSN
FROM TB_STUDENT;

-- 7. 의학과 김명훈 학생 2005년 1학기 '피부생리학' 학점 3.5로 변경
UPDATE TB_GRADE
SET POINT = 3.5
WHERE STUDENT_NO = (SELECT STUDENT_NO
                    FROM TB_STUDENT
                         JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                    WHERE STUDENT_NAME = '김명훈'
                          AND DEPARTMENT_NAME = '의학과')
      AND TERM_NO LIKE '200501'
      AND CLASS_NO = (SELECT CLASS_NO 
                      FROM TB_CLASS
                      WHERE CLASS_NAME = '피부생리학');            


-- 8. 성적 테이블(TB_GRADE)에서 휴학생들의 성적항복 제거
DELETE FROM TB_GRADE 
WHERE STUDENT_NO IN (SELECT STUDENT_NO
                     FROM TB_STUDENT
                     WHERE ABSENCE_YN = 'Y');

COMMIT;

