-- 1. 70년대 생(1970~1979) 중 여자 & 전씨 사원 이름, 주민번호, 부서 명, 직급 조회
-- [오라클 구문]
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE E, DEPARTMENT, JOB J
WHERE DEPT_ID = DEPT_CODE
      AND E.JOB_CODE = J.JOB_CODE
      AND (SUBSTR(EMP_NO, 1, 2) BETWEEN '70' AND '79')
      AND EMP_NAME LIKE '전%';
      
-- [ANSI 표준 구문]
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
     JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
     JOIN JOB USING (JOB_CODE)
WHERE SUBSTR(EMP_NO, 1, 2) BETWEEN '70' AND '79'
      AND EMP_NAME LIKE '전%';
    
-- 2. 나이 상 가장 막내 사원코드, 사원명, 나이, 부서명, 직급명 조회
SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM  SYSDATE)-(SUBSTR(EMP_NO, 1, 2)+1900) 나이,
       DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
     JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
     JOIN JOB USING (JOB_CODE);


-- 3. 이름에 '형'이 들어가는 사원의 사원코드, 사원명, 직급 조회
-- [오라클 구문]
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
      AND EMP_NAME LIKE '%형%';

-- [ANSI 표준 구문]
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE
    JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

-- 4. 부서코드 D5 OR D6인 사원의 사원명, 직급명, 부서코드, 부서명 조회
-- [오라클 구문]
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE DEPT_CODE IN ('D5', 'D6')
      AND E.JOB_CODE = J.JOB_CODE
      AND E.DEPT_CODE = D.DEPT_ID;
      
-- [ANSI 표준 구문]
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE
     JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
     JOIN JOB USING (JOB_CODE)
WHERE DEPT_CODE IN ('D5', 'D6');

-- 5. 보너스를 받는 사원의 사원명, 부서명, 지역명 조회
-- [오라클 구문]
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE, DEPARTMENT , LOCATION
WHERE DEPT_CODE = DEPT_ID
      AND LOCATION_ID = LOCAL_CODE
      AND BONUS IS NOT NULL;

-- [ANSI 표준 구문]
SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
     JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
     JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE BONUS IS NOT NULL;

-- 6. 사원명,직급명, 부서명, 지역명 조회
-- [오라클 구문]
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT, JOB J, LOCATION 
WHERE DEPT_CODE = DEPT_ID
      AND LOCATION_ID = LOCAL_CODE
      AND E.JOB_CODE = J.JOB_CODE;

-- [ANSI 표준 구문]
SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
    JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
    JOIN JOB USING (JOB_CODE)
    JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE);

-- 7. 한국이나 일본에서 근무중인 사원의 사원명, 부서명, 지역명, 국가명 조회
SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
     JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
     JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
     JOIN NATIONAL USING (NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국', '일본');

-- 8. 한 사원과 같은 부서에서 일하는 사원의 이름 조회
--SELECT EMP_NAME, DEPT_CODE, EMP_NAME

-- 9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원 이름, 직급명, 급여조회(NVL이용)
SELECT EMP_NAME, JOB_NAME, NVL(SALARY, '')
FROM EMPLOYEE
    JOIN JOB USING (JOB_CODE)
WHERE JOB_CODE IN ('J4', 'J7');

-- 10. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서명, 직급, 입사일, 순위 조회
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM 순위
FROM (SELECT *
      FROM EMPLOYEE
      ORDER BY SALARY DESC)
     JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
     JOIN JOB USING (JOB_CODE)
WHERE ROWNUM <= 5;


-- 11. 부서 별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서명, 부서별 급여 합계 조회
-- 11-1. JOIN과 HAVING 사용

-- 11-2. 인라인 뷰 사용

-- 11-3. WITH 사용

-- 12. 부서명과 부서별 급여 합계 조회
SELECT DEPT_TITLE, SUM(SALARY)
FROM 

-- 13. WITH를 이용하여 급여 합과 급여 평균 조회


