-- 학생이름과 주소지 표시.
-- 단, 출력 헤더는 "학생 이름", "주소지", 이름으로 오름차순 
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

-- 휴학중인 학생 이름과 주민번호 나이 적은 순서로 출력
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3. 주소지가 강원도 OR 경기도인 학생들 중 1900년대 학번을 가진 학생 이름, 학번, 주소, 이름으로 오름차순 
-- 단, 출력 헤더는 "학생이름", "학번", "거주지 주소"
SELECT STUDENT_NAME "학생 이름",  STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%')
      AND STUDENT_NO NOT LIKE 'A%'
ORDER BY STUDENT_NAME;

-- 4. 현재 법학과 교수 중 가장 나이가 많은 사람 순으로 교수 이름, 주민번호 출력
-- [오라클 구문]
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR P, TB_DEPARTMENT D
WHERE P.DEPARTMENT_NO = D.DEPARTMENT_NO
      AND DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

-- [ANSI 표준 구문]
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
     JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN;

-- 5.2004년 2학기에 'C311800' 과목 수강한 학생들 학점 조회
-- 학점 높을 학생 순으로 , 학점이 같으면 학번이 낮은 학생부터 출력
-- [오라클 구문]
SELECT STUDENT_NO, POINT
FROM TB_STUDENT, TB_GRADE
ORDER BY POINT





